services:

    flux_se.sylius_stripe.provider.web_elements.create.params:
        class: FluxSE\SyliusStripePlugin\Provider\CompositeParamsProvider
        arguments:
            - !tagged_iterator flux_se.sylius_stripe.provider.web_elements.create.inner_params

    flux_se.sylius_stripe.provider.web_elements.create.amount:
        class: FluxSE\SyliusStripePlugin\Provider\WebElements\Create\AmountProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -100

    flux_se.sylius_stripe.provider.web_elements.create.currency:
        class: FluxSE\SyliusStripePlugin\Provider\WebElements\Create\CurrencyProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -200

    flux_se.sylius_stripe.provider.web_elements.create.capture_method.manual:
        class: FluxSE\SyliusStripePlugin\Provider\PaymentIntentCaptureMethodManualProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -400

    flux_se.sylius_stripe.provider.web_elements.create.metadata:
        class: FluxSE\SyliusStripePlugin\Provider\CompositeMetadataParamsProvider
        arguments:
            - !tagged_iterator flux_se.sylius_stripe.provider.web_elements.create.metadata
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.inner_params
              priority: -500

    flux_se.sylius_stripe.provider.web_elements.create.metadata.token_hash:
        class: FluxSE\SyliusStripePlugin\Provider\TokenHashMetadataProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.metadata
              priority: -100

    flux_se.sylius_stripe.provider.web_elements.create.metadata.order:
        class: FluxSE\SyliusStripePlugin\Provider\OrderMetadataProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.metadata
              priority: -200

    flux_se.sylius_stripe.provider.web_elements.create.metadata.product_categories:
        class: FluxSE\SyliusStripePlugin\Provider\ProductCategoriesMetadataProvider
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.metadata
              priority: -250

    flux_se.sylius_stripe.provider.web_elements.create.metadata.first_order_flag:
        class: FluxSE\SyliusStripePlugin\Provider\FirstOrderFlagMetadataProvider
        arguments:
            - '@sylius.repository.order'
        tags:
            - name: flux_se.sylius_stripe.provider.web_elements.create.metadata
              priority: -300
