services:
    flux_se.sylius_stripe.shop.express_checkout.payload_reader:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\Payload\ExpressCheckoutPayloadReader
    FluxSE\SyliusStripePlugin\ExpressCheckout\Payload\ExpressCheckoutPayloadReaderInterface: '@flux_se.sylius_stripe.shop.express_checkout.payload_reader'

    flux_se.sylius_stripe.shop.express_checkout.shipping_rate_assembler:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\Shipping\ShippingRateAssembler
        arguments:
            - '@sylius.calculator.shipping'
    FluxSE\SyliusStripePlugin\ExpressCheckout\Shipping\ShippingRateAssemblerInterface: '@flux_se.sylius_stripe.shop.express_checkout.shipping_rate_assembler'

    flux_se.sylius_stripe.shop.express_checkout.capture_payment_request_dispatcher:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\Payment\CapturePaymentRequestDispatcher
        arguments:
            - '@sylius.factory.payment_request'
            - '@sylius.payment_request.command_bus'
            - '@sylius.repository.payment_request'
    FluxSE\SyliusStripePlugin\ExpressCheckout\Payment\CapturePaymentRequestDispatcherInterface: '@flux_se.sylius_stripe.shop.express_checkout.capture_payment_request_dispatcher'

    flux_se.sylius_stripe.shop.express_checkout.configuration_provider:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\ConfigurationProvider
        arguments:
            - '@sylius.context.cart'
            - '@sylius.context.channel'
            - '@flux_se.sylius_stripe.resolver.express_checkout_payment_method'
    FluxSE\SyliusStripePlugin\ExpressCheckout\ConfigurationProviderInterface: '@flux_se.sylius_stripe.shop.express_checkout.configuration_provider'

    flux_se.sylius_stripe.shop.express_checkout.shipping_options_calculator:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\ShippingOptionsCalculator
        arguments:
            - '@sylius.context.cart'
            - '@sylius.order_processing.order_processor'
            - '@sylius.resolver.shipping_methods'
            - '@sylius.repository.shipping_method'
            - '@flux_se.sylius_stripe.normalizer.express_checkout_address'
            - '@flux_se.sylius_stripe.shop.express_checkout.payload_reader'
            - '@flux_se.sylius_stripe.shop.express_checkout.shipping_rate_assembler'
    FluxSE\SyliusStripePlugin\ExpressCheckout\ShippingOptionsCalculatorInterface: '@flux_se.sylius_stripe.shop.express_checkout.shipping_options_calculator'

    flux_se.sylius_stripe.shop.express_checkout.order_completer:
        class: FluxSE\SyliusStripePlugin\ExpressCheckout\OrderCompleter
        arguments:
            - '@sylius.context.cart'
            - '@sylius.context.channel'
            - '@flux_se.sylius_stripe.resolver.express_checkout_payment_method'
            - '@flux_se.sylius_stripe.normalizer.express_checkout_address'
            - '@flux_se.sylius_stripe.shop.express_checkout.payload_reader'
            - '@sylius.resolver.customer'
            - '@sylius_abstraction.state_machine'
            - '@sylius.factory.payment'
            - '@sylius.repository.shipping_method'
            - '@flux_se.sylius_stripe.shop.express_checkout.capture_payment_request_dispatcher'
            - '@flux_se.sylius_stripe.shop.provider.after_url'
            - '@request_stack'
    FluxSE\SyliusStripePlugin\ExpressCheckout\OrderCompleterInterface: '@flux_se.sylius_stripe.shop.express_checkout.order_completer'
