services:
    flux_se.sylius_stripe.stripe.secret_key.legacy_key_detector:
        class: FluxSE\SyliusStripePlugin\Stripe\SecretKey\LegacyKeyDetector
    FluxSE\SyliusStripePlugin\Stripe\SecretKey\LegacyKeyDetectorInterface:
        alias: flux_se.sylius_stripe.stripe.secret_key.legacy_key_detector
