flux_se_sylius_stripe_express_checkout_configuration:
    path: /express-checkout/configuration
    methods: [GET]
    defaults:
        _controller: FluxSE\SyliusStripePlugin\Controller\Shop\ExpressCheckout\ConfigurationAction

flux_se_sylius_stripe_express_checkout_shipping_rates:
    path: /express-checkout/shipping-rates
    methods: [POST]
    defaults:
        _controller: FluxSE\SyliusStripePlugin\Controller\Shop\ExpressCheckout\ShippingRatesAction

flux_se_sylius_stripe_express_checkout_confirm:
    path: /express-checkout/confirm
    methods: [POST]
    defaults:
        _controller: FluxSE\SyliusStripePlugin\Controller\Shop\ExpressCheckout\ConfirmAction
